#!/bin/bash

# Containers.
CONTAINERS_NAME="
  centos_setup_cache
  centos_setup_application
  centos_setup_search
  centos_setup_database
  centos_setup_mail
"

# Stop all containers
docker stop $CONTAINERS_NAME

# Delete all containers
docker rm -f $CONTAINERS_NAME

# Delete all images
# docker rmi -f $CONTAINERS_NAME
