version: '2'

# Network.
networks:
  prodnetwork:
    driver: bridge

# Volumes.

# Services.
services:
  # Application
  centos_application:
    image: centos:7
    command: bash /var/application/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    #depends_on:
    volumes:
      - ./containers/application:/var/application
  # Search
  centos_search:
    image: centos:7
    command: bash /var/search/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    #depends_on:
    volumes:
      - ./containers/search:/var/search
  # Cache
  centos_cache:
    image: centos:7
    command: bash /var/cache/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    expose:
      - "180:80"
      - "11211"
    #depends_on:
    volumes:
      - ./containers/cache:/var/cache
  # Database
  centos_database:
    image: centos:7
    command: bash /var/database/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    #depends_on:
    volumes:
      - ./containers/database:/var/database
