version: '2'

# Network.
networks:
  prodnetwork:
    driver: bridge

# Volumes.

# Services.
services:
  # Application
  centos_application:
    image: centos:7
    command: bash /var/application/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    #depends_on:
    volumes:
      - ./containers/application:/var/application
    container_name: centos_setup_application
  # Search
  centos_search:
    image: centos:7
    command: bash /var/search/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    #depends_on:
    volumes:
      - ./containers/search:/var/search
    container_name: centos_setup_search
  # Cache
  centos_cache:
    image: centos:7
    command: bash /var/cache/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    ports:
      - "180:80"
      - "11211:11211"
    expose:
      - "80"
      - "11211"
    #depends_on:
    volumes:
      - ./containers/cache:/var/cache
    container_name: centos_setup_cache
  # Database
  centos_database:
    image: centos:7
    command: bash /var/database/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
    ports:
      - "13306:3306"
    expose:
      - "3306"
    #depends_on:
    volumes:
      - ./containers/database:/var/database
    container_name: centos_setup_database
  # Mail
  centos_mail:
    image: catatnight/postfix
    command: bash /var/mail/bootstrap.sh
    #ports:
    networks:
      - prodnetwork
    environment:
      container: docker
      maildomain: mail.centos-setup.server
      smtp_user: user:pwd
    ports:
      - "225:25"
    expose:
      - "25"
    #depends_on:
    volumes:
      - ./containers/mail:/var/mail
    container_name: centos_setup_mail
